### ISSUE TITLE
Add new release

### ISSUE THREAD

**Issue by lanrat** [bachya/py17track#79]
**Describe the bug**

Not really a bug, but would it be possible for you to release a new version of py17track to pypi so that projects that use this library can get some of the newer features/fixes?

Thanks.

**Comment by bachya** [comment]
There haven't been any features/bug fixes since the last release—only dependency bumps:

- Update all dependencies (#77)
- Update codecov/codecov-action action to v3 (#75)
- Upgrade black to 22.3.0 (#76)
- Update all dependencies (#73)
- Update dependency pytest-aiohttp to v1 (#71)

Are you running into a specific issue?

**Comment by lanrat** [comment]
Oh, nevermind.

I was monitoring the wrong branch.
